-- Migration: create reviews table with approval system
-- Run this in Supabase SQL editor or via supabase CLI

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  name text,
  email text,
  message text not null,
  rating int check (rating >= 1 and rating <= 5) default 5,
  photos jsonb default '[]'::jsonb,
  approved boolean default false,
  created_at timestamptz default now()
);

-- Enable RLS
alter table public.reviews enable row level security;

-- Policy: anyone can insert reviews (they will be pending approval)
create policy "anon_insert_reviews" on public.reviews
  for insert
  with check (true);

-- Policy: only show approved reviews to public
create policy "public_read_approved" on public.reviews
  for select
  using (approved = true);

-- Note: Admin access (view all/update/delete) should be done via a secure backend
-- or using the service_role key. Do NOT expose the service_role key in client code in production.
